variables:

stages:
  - build
  - test

build:
  image: omnijarstudio/rust:linux-musl
  stage: build
  script:
    - echo "Building release artifact"
    - make build
    - mkdir -p artifacts
    - mv target/x86_64-unknown-linux-musl/release/vor ./artifacts/
    - mv target/x86_64-unknown-linux-musl/release/vor-daemon ./artifacts/
    - make clean
  artifacts:
    paths:
    - ./artifacts
    expire_in: 1 week
  tags:
    - docker
  when: manual
  only:
    - release
  artifacts:
    paths:
      - ./artifacts
    expire_in: 1 week

review:
  image: omnijarstudio/rust:linux-musl
  stage: test
  script:
    - echo "Reviewing service"
    - make build
    - make test
    - make clean
  only:
    - branches
  except:
    - master

test:
  image: omnijarstudio/rust:linux-musl
  stage: test
  script:
    - echo "Testing service"
    - make build
    - make test
    - mkdir -p artifacts
    - mv target/x86_64-unknown-linux-musl/debug/vor ./artifacts/
    - mv target/x86_64-unknown-linux-musl/debug/vor-daemon ./artifacts/
    - make clean
  tags:
    - docker
  only:
    - master
  dependencies:
    - build
